export enum UserRole {
  ADMIN = 'ADMIN',
  LINGUIST = 'LINGUIST',
}

export enum StateUser {
  UNCONFIRMED = 'UNCONFIRMED',
  CONFIRMED = 'CONFIRMED',
  INVITED = 'INVITED',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  DELETED = 'DELETED',
}
